/* Generated by AN DISI Unibo */ 
package it.unibo.sync_actor

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sync_actor ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var DMIN = 10  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_events", cond=doswitch() )
				}	 
				state("wait_events") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
											   var Dist = payloadArg(0).toInt() 
											   var Obstacle = (Dist < DMIN)
								if(  Obstacle  
								 ){forward("sync_on", "sync_on(S)" ,"firefly1" ) 
								forward("sync_on", "sync_on(S)" ,"firefly2" ) 
								forward("sync_on", "sync_on(S)" ,"firefly3" ) 
								forward("sync_on", "sync_on(S)" ,"firefly4" ) 
								forward("sync_on", "sync_on(S)" ,"firefly5" ) 
								forward("sync_on", "sync_on(S)" ,"firefly6" ) 
								}
								if(  !Obstacle  
								 ){forward("sync_off", "sync_off(S)" ,"firefly1" ) 
								forward("sync_off", "sync_off(S)" ,"firefly2" ) 
								forward("sync_off", "sync_off(S)" ,"firefly3" ) 
								forward("sync_off", "sync_off(S)" ,"firefly4" ) 
								forward("sync_off", "sync_off(S)" ,"firefly5" ) 
								forward("sync_off", "sync_off(S)" ,"firefly6" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t10",targetState="wait_events",cond=whenEvent("data"))
				}	 
			}
		}
} 
