/* Generated by AN DISI Unibo */ 
package it.unibo.sync_actor

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sync_actor ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
			   var Timer_sync  = 10000L   
			   var DMIN = 10
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("$name | Sincronizzazione avviata")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", Timer_sync )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="sync_sec",cond=whenTimeout("local_tout_"+name+"_s0"))   
					transition(edgeName="t01",targetState="handle_sonar",cond=whenEvent("data"))
				}	 
				state("sync_sec") { //this:State
					action { //it:State
						CommUtils.outred("$name | Sincronizzazione (10s)")
						forward("sync_on", "sync_on(S)" ,"firefly1" ) 
						forward("sync_on", "sync_on(S)" ,"firefly2" ) 
						forward("sync_on", "sync_on(S)" ,"firefly3" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_events", cond=doswitch() )
				}	 
				state("wait_events") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="handle_sonar",cond=whenEvent("data"))
				}	 
				state("handle_sonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Dist = payloadArg(0).toInt()  
								if(  Dist < DMIN  
								 ){CommUtils.outred("$name | Ostacolo rilevato")
								forward("sync_on", "sync_on(S)" ,"firefly1" ) 
								forward("sync_on", "sync_on(S)" ,"firefly2" ) 
								forward("sync_on", "sync_on(S)" ,"firefly3" ) 
								}
								if(  Dist >= DMIN  
								 ){CommUtils.outred("$name | Ostacolo non rilevato")
								forward("sync_off", "sync_off(S)" ,"firefly1" ) 
								forward("sync_off", "sync_off(S)" ,"firefly2" ) 
								forward("sync_off", "sync_off(S)" ,"firefly3" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_events", cond=doswitch() )
				}	 
			}
		}
} 
